### PR TITLE
Resolve Let students view questions after "close time" #68

### LINKED ISSUE #68: Let students view questions after "close time"
Hi,

now, when the "close time" has passed, the activity is considered completely closed and students cannot view any of the questions submitted.
It could be interesting to let teachers decide if questions should be still available to students in "read-only mode" (without any action like submit, vote, ecc... available).

Maybe a single yes/no config in the Availability section could be enough.

Do you think this could be done easily? Could be useful a help to develop this feature?

Kind regards,
Giorgio

### PR DESCRIPTION
**Pull request by Kemmotar83**
Resolves #68

### CODE REVIEW

**Comment by Kemmotar83** [comment]
Hi @drachels ,

I've worked on the issue #68 and everything works as expected. I've also added one behat feature test (tested locally).

As I said before, I needed to add a specific setting in mod form to control visibility, so I had to bump the version. The default value of this setting is No, leaving the default behavior as it was till now.

Giorgio

**Comment by drachels** [comment]
I just took a look at the code, and what you have appears okay, except you forgot to include your new database field in the the backup file, backup_hotquestion_stepslib.php. I have completed the merge and will add the missing field in the backup file.

**Comment by Kemmotar83** [comment]
Hi @drachels, my bad. Sorry for that.

**Comment by drachels** [comment]
I think it is going to take me a couple of days to actually try and implement this as I notice that you have created three new functions in locallib.php instead of just using and improving/adding to, the one in ...classes/local/results.php.

The time delay is because I still have a couple of MooTyper tests I have to do/try before I can spend more time on this.

**Comment by Kemmotar83** [comment]
Take the time you need and change the code as you like.
Thank you again for maintaining this useful plugin.

**Comment by drachels** [comment]
Just to let you know, yesterday I was able to start working on HotQuestion again and have a v4.1.5 BETA version installed on a Moodle 3.11 dev site at https://www.drachels.com/moodle311/course/view.php?id=5
The log in page show which user names you can use. I think somehow the last merge got "lost" so I am just going to add everything back, manually.

**Comment by drachels** [comment]
Just added my latest code to the site mentioned in my last entry. It prevents students from adding or removing votes when the activity is closed, but view after close is enabled. It has not been posted to github yet. Teachers and admins can still make changes to their votes, add or remove.

I have to quit for the day. Got to go grocery shopping as I have run too low on food for our dog.

**Pull request merged**
